# Generated by Django 4.2.4 on 2023-08-11 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initialize', '0003_pdf_upload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pdf_upload',
        ),
    ]
