# Generated by Django 4.2.4 on 2023-08-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initialize', '0004_delete_pdf_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=400)),
                ('pdf', models.FileField(upload_to='pdf/')),
            ],
        ),
    ]
