# Generated by Django 4.2.4 on 2023-08-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initialize', '0008_alter_pdf_upload_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf_upload',
            name='name',
            field=models.CharField(default='xyz', max_length=50),
        ),
    ]
