# Generated by Django 4.2.4 on 2023-08-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initialize', '0009_pdf_upload_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf_upload',
            name='experience',
            field=models.CharField(default='xyz', max_length=400),
        ),
        migrations.AddField(
            model_name='pdf_upload',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pdf_upload',
            name='skills',
            field=models.CharField(default='xyz', max_length=400),
        ),
    ]
