# Generated by Django 4.2.4 on 2023-08-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initialize', '0010_pdf_upload_experience_pdf_upload_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf_upload',
            name='a1',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AddField(
            model_name='pdf_upload',
            name='a2',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AddField(
            model_name='pdf_upload',
            name='a3',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AddField(
            model_name='pdf_upload',
            name='a4',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AddField(
            model_name='pdf_upload',
            name='a5',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AddField(
            model_name='pdf_upload',
            name='q1',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AddField(
            model_name='pdf_upload',
            name='q2',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AddField(
            model_name='pdf_upload',
            name='q3',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AddField(
            model_name='pdf_upload',
            name='q4',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AddField(
            model_name='pdf_upload',
            name='q5',
            field=models.CharField(default=' ', max_length=1000),
        ),
    ]
