# Generated by Django 4.2.4 on 2023-08-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initialize', '0011_pdf_upload_a1_pdf_upload_a2_pdf_upload_a3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf_upload',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
